# Generated by Django 4.0.3 on 2022-03-26 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urlredirect',
            options={'verbose_name': 'URL Redirect', 'verbose_name_plural': "URL's Redirect"},
        ),
        migrations.CreateModel(
            name='UrlLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('origin', models.URLField(max_length=512)),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True)),
                ('host', models.CharField(blank=True, max_length=512, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('url_redirect', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='core.urlredirect')),
            ],
            options={
                'verbose_name': 'URL Log',
                'verbose_name_plural': "URL's Log",
            },
        ),
    ]
