# Generated by Django 4.0.3 on 2022-03-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_urlredirect_options_urllog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urllog',
            name='origin',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
